services:
  app:
    image: egfective-mobile
    restart: always
    build:
      context: .
    ports:
      - 8080:8080
    networks:
      - backend
    depends_on:
      - db
  
  db:
    image: postgres:latest
    restart: always
    ports:
      - 8000:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge